# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:





jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: portainer-home
    runs-on: portainer-home
    steps:
    - name: move-to-html
      run: "mv * /home/administrator/actions-runner/test"
    
          
